version: '2.1'

parameters:
  generate-repos-metadata:
    type: boolean
    default: false

orbs:
  node: circleci/node@7.2.1
  github-utils: trustedshops-public/github-utils@1.3.1

commands:
  build-site:
    steps:
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Build with vite
          command: yarn run build
      - persist_to_workspace:
          root: .
          paths:
            - build/

jobs:
  generate-repos-metadata:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Generate repos metadata
          command: node scripts/generate-repos-metadata.js
      - store_artifacts:
          path: public/repos-metadata.json
      - persist_to_workspace:
          root: .
          paths:
            - public/repos-metadata.json
  build:
    executor: node/default
    steps:
      - checkout
      - build-site
  build-metadata:
    executor: node/default
    steps:
      - checkout
      # puts public/repos-metadata.json from generate-repos-metadata into public/
      - attach_workspace:
          at: .
      - build-site
  deploy:
    executor: node/default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - github-utils/publish_github_pages:
          folder: build/
          git_commit_author_email: 'no-reply@trustedshops.com'
          git_commit_author_name: 'trustedshops-public-cns-bot'
          nojekyll: true
          cname: opensource.trustedshops.com

workflows:
  main:
    unless: << pipeline.parameters.generate-repos-metadata >>
    jobs:
      - build
      - deploy:
          context:
            - semantic-release
          requires:
            - build
          filters:
            branches:
              only:
                - main
  repos-metadata:
    when: << pipeline.parameters.generate-repos-metadata >>
    jobs:
      - generate-repos-metadata
      - build-metadata:
          requires:
            - generate-repos-metadata
      - deploy:
          context:
            - semantic-release
          requires:
            - build
